###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: track-them-all-mysql
      volumes:
        - /private/var/www/track-them-all:/var/www/track-them-all
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=track-them-all
        - MYSQL_USER=mathieu
        - MYSQL_PASSWORD=secret
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: track-them-all-webserver
      volumes:
          - /private/var/www/track-them-all:/var/www/track-them-all
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      extra_hosts:
       - "track-them-all.com: 127.0.0.1"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: track-them-all-php-fpm
      volumes:
        - /private/var/www/track-them-all:/var/www/track-them-all
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      extra_hosts:
       - "track-them-all.com: 127.0.0.1"
